# Generated by Django 4.1.6 on 2023-02-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectType', models.CharField(max_length=200)),
                ('objectId', models.CharField(max_length=200)),
                ('copay', models.IntegerField()),
                ('_org', models.CharField(max_length=200)),
                ('deductible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectType', models.CharField(max_length=200)),
                ('objectId', models.CharField(max_length=200)),
                ('_org', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectType', models.CharField(max_length=200)),
                ('objectId', models.CharField(max_length=200)),
                ('_org', models.CharField(max_length=200)),
                ('name', models.IntegerField()),
            ],
        ),
    ]
